Revert "chore: update repo"
This reverts commit 15c5dc184e0432f05e427b2bf139793e67f445a4.

diff --git a/debian/local/Xsession b/debian/local/Xsession
--- a/debian/local/Xsession
+++ b/debian/local/Xsession
@@ -94,7 +94,9 @@ fi
 
 exec >>"$ERRFILE" 2>&1
 
-echo "$PROGNAME: X session started for $LOGNAME at $(date)"
+# This echo might fail as we just redirect stderr.
+# Just ignore that failure here.
+echo "$PROGNAME: X session started for $LOGNAME at $(date)" || true
 
 # sanity check; is our session script directory present?
 if [ ! -d "$SYSSESSIONDIR" ]; then
